### ISSUE TITLE
Bug: Turrets attack hidden mimics

### ISSUE THREAD

**Issue by Caaz** [Caaz/rimworld-typhon#104]
# Description
At the moment, turrets can attack (and kill) hidden mimics. They shouldn't be able to see them, so that shouldn't happen.

Looks like the function responsible for choosing targets uses `Verse.AI.AttackTargetFinder.BestAttackTarget`, which uses `GenHostility.HostileTo`, which is patched, but only checks the first argument. In this case, the searcher being the building, and the target being the mimic, isn't covered. `Thing b` should be checked in the patch for turrets to not target them.

This probably applies to more than just turrets.

**Comment by RedPine91** [comment]
It's not just turrets, EVERYTHING can see and attack hidden mimics.  This lets raiders with revolvers solo an entire map swarming with mimics and cystoids.

[# Log](https://gist.github.com/312dc5f9596b1e67b53df9a730f48f3a)
