### ISSUE TITLE
Add Phantom Genesis psycast

### ISSUE THREAD

**Issue by Caaz** [Caaz/rimworld-typhon#110]
# Description
[Phantom Genesis](https://prey.fandom.com/wiki/Phantom_Genesis) spawns a friendly neighborhood phantom to fight alongside your colonists. In prey, the friendly phantom will wander, and it's probably easiest to keep that behavior in Rimworld as well

## Technical thoughts
Going to have to rework phantom's thinktree to act differently if they're part of the player's colony. can't have em go on a massacre.
It should take a lot of psy....whatever to cast this, and possibly keep using it so long as the phantom is active. Additionally, phantoms should either die or turn hostile when the caster who created them is downed/killed.

# Art Needed
Will likely need some kind of icon for this ability. There's likely an icon for it in prey. Screenshot eventually.

# Audio Needed
Might be a nice idea to have an audio asset for the ability itself, if no applicable one exists currently.

**Comment by Polioguy** [comment]
![Phantomgenesis-PhantomPale](https://user-images.githubusercontent.com/63909681/206886549-1c1d9a67-4b6d-43a7-bcd3-5e1efb168d90.png)
![Phantomgenesis-PhantomPurple](https://user-images.githubusercontent.com/63909681/206886555-42ac0501-aa87-4587-863c-b2f1db15f0c9.png)
![Phantomgenesis-SkullPale](https://user-images.githubusercontent.com/63909681/206886557-5d00cb4a-86e6-4060-a333-72cb4ccf1284.png)
![Phantomgenesis-SkullPurple](https://user-images.githubusercontent.com/63909681/206886561-c22fb1f1-037c-4f09-86c7-304f0801f225.png)
Various Icon Variants for Psycast

**Comment by Caaz** [comment]
This, and the others you've provided are bad ass, I'll attempt to implement them but I'm also in the middle of reworking the mod to be a little more inviting to more developers to work on. 

With the changes in 1.4 I'm exploring better ways to introduce abilities and such, so this'll really help me play with getting it working. 

Big thank you, I'm going to be doing a lot of work on Typhon in the coming weeks.

**Comment by Caaz** [comment]
For future reference, I think I'm gonna go with that second one, the deeper purples are just my favorite color, and I think the phantom is good UI wise, to not be confused with anything else rimworld-modding-related. 

Got the ability coded up, and it works beautifully.  Again, huge thank you. I'm going to be throwing up some more abilities. That's my main focus with the rewrite at least.

**Comment by Caaz** [comment]
I take it back, the skull might be good for this ability, the phantom might be good for the Phantom shift ability.
