### ISSUE TITLE
Bug: Mimics attack mimics 

### ISSUE THREAD

**Issue by RedPine91** [Caaz/rimworld-typhon#134]
In a complicated fight involving multiple mimics, smoke launchers, and fire, mimics aggroed on other mimics.

[# Log](https://gist.github.com/312dc5f9596b1e67b53df9a730f48f3a)

![image](https://user-images.githubusercontent.com/30212969/167791394-5c6a4cfb-eee5-4cb1-a73e-d6f6799e4510.png)

**Comment by Caaz** [comment]
Actually this one's an expected intended behavior.
https://www.youtube.com/watch?v=lO0zLT5Bruk

It's how a weaver gets created. If there are a certain number of Mimics around, a mimic will decide to call other mimics to attack it, forcing it to become a weaver.
https://github.com/Caaz/rimworld-typhon/blob/main/Source/JobDriver/CreateWeaver.cs#L30
