### ISSUE TITLE
Bug: typhon have terrible vision

### ISSUE THREAD

**Issue by RedPine91** [Caaz/rimworld-typhon#135]
Typhon have terrible vision.  The pictured phantom only just now got involved in the fight, despite having been spawned from a corpse during this fight.  Same for weavers and mimics, they seem remain completely unaware of anything that isn't extremely close to them - even if they are being dealt damage.

![image](https://user-images.githubusercontent.com/30212969/167791922-12081ce9-16f5-40ae-b4e7-09bfe9ed897c.png)

https://gist.github.com/HugsLibRecordKeeper/312dc5f9596b1e67b53df9a730f48f3a

**Comment by RedPine91** [comment]
![image](https://user-images.githubusercontent.com/30212969/167792371-65e0535a-52ec-4085-9a76-737064d7cd2a.png)

Case in point: Phantom up top is attacking a corpse, weaver to the west is wandering aimlessly while getting shot, and the two phantoms and all the mimics surrounding the weaver are too far to see either shooter.

**Comment by Caaz** [comment]
This one's interesting. So each typhon have a range value of what they would attack
https://github.com/Caaz/rimworld-typhon/blob/1236be0253be611d79059f773e7a6439af4595dd/Source/Utilities/TyphonUtility.cs#L80-L87

This value is used when they have their standard attack pawn job, which usually happens while they're wandering around.

If what you want is for them to attack together, that might be doable via the hivemind feature. That way, when a phantom finds something to attack, it'd broadcast it to other typhon, causing backup to arrive. Phantoms don't currently have the hivemind enabled, so it's something I could add I believe.
