### ISSUE TITLE
Alternative Cystoid explosion

### ISSUE THREAD

**Issue by Caaz** [Caaz/rimworld-typhon#146]
# Description
Cystoids cause radiation damage in Prey when they explode, not fire. This might be able to be replicated with radiation build up. Worth looking into.

Additionally, we should probably remove cystoid corpses on death.

**Comment by RedPine91** [comment]
Radiation=Toxic in Rimworld.

The current Cystoids have an incredibly high chance of doing more harm to the typhon than good by setting everything on fire.  Replacing their fire damage with Toxic, and making typhon immune to Toxic, would prevent reduce friendly fire and make cystoids far more dangerous.

**Comment by Caaz** [comment]
Yeah typo here actually I meant to type toxic build up. I donno if I want them to be immune to toxic. One thing kinda important about cystoids is that blowing up one should chain reaction them to other cystoids. I haven't dug into it yet but I figure I might be able to just apply a point of damage which'd cause them to die anyway.
