### ISSUE TITLE
Add Cystoid Nests

### ISSUE THREAD

**Issue by Caaz** [Caaz/rimworld-typhon#70]
![Cystoid_Nest_Research](https://user-images.githubusercontent.com/7529595/157150138-8ee5ff44-7c57-4a8c-9c1b-21d5110f15e3.png)
[Cystoid Nests](https://prey.fandom.com/wiki/Cystoid_Nest) Are created by Weavers occasionally, and spawn Cystoids. 
- Add Defs
- Add Sounds
- Add Textures

Depends on #14
 
 ## Assets Needed
 A single texture for this object, It's stationary, similar to the insect hive. Just sits there and spawns cystoids I guess.
 
 In prey, these usually are attached to a ceiling or floating in space. I think it's fair to assume in rimworld they'll probably be on the ground somewhere, so some artistic liberty will have to be taken for that to make sense.
![nest](https://user-images.githubusercontent.com/7529595/157150649-e3d9ce81-079e-41d6-a5ee-0027861f8040.png)

**Comment by Woof6968** [comment]
maybe make this spawn around that potential space station that could occur? (i was the guy who said that in the steam comments)

**Comment by Caaz** [comment]
Yeah I'll probably have some of these spawn in that, though it's said weavers create these in general so they'll probably be the main thing to spawn them anywhere
