### ISSUE TITLE
Bug: Humanoid Alien Races causes mimics to not go invisible

### ISSUE THREAD

**Issue by lag42** [Caaz/rimworld-typhon#97]
# Description
when [HAR fix for Yayo Animation is installed](https://steamcommunity.com/sharedfiles/filedetails/?id=2579147061)(no alien races using that framework have to be installed), mimics are visible whilst hiding, though they have no problems mechanically with this one
![Screenshot_35](https://user-images.githubusercontent.com/22325011/160683457-6cb6e2bb-d4f5-48d1-bd12-019f6355c393.png)

# Log
https://gist.github.com/HugsLibRecordKeeper/e489f11169d9b9e955b684ad36f21628

**Comment by Caaz** [comment]
Absolute hype. I've had a few reports on this but no modlist or log or anything to figure out what was causing it. I'll take a look and see what i can do.

**Comment by lag42** [comment]
took me a while to nail down myself, until i had an epiphany that it could be yayo's animation, which wasn't it, then i realized har fix might be catching their visuals

**Comment by Caaz** [comment]
Turns out it's not even Yayo or that HAR fix, it's HAR itself according to your log and me just testing HAR alone. 
```
PawnGraphicSet.ResolveAllGraphics: PRE: AlienRace.HarmonyPatches.ResolveAllGraphicsPrefix
```
Looks like HAR is patching ResolveAllGraphics which is what mimics use to switch textures on the fly. big oof. This may take a bit.

**Comment by Caaz** [comment]
Better news, it wasn't that patch, it was the ChangeKind being patched.
```cs
 public static bool ChangeKindPrefix(Pawn __instance, PawnKindDef newKindDef) =>
  __instance.kindDef == PawnKindDefOf.WildMan || newKindDef == PawnKindDefOf.WildMan;
```
This'll wind up getting fixed in HAR actually, so I don't need to do anything to solve this myself. the best kind of bug.

**Comment by Caaz** [comment]
Fixed as of https://github.com/erdelf/AlienRaces/commit/55406c001790eb658b5f99b5db51dbaa868f78f5
